# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170322_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
