# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-04-01 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170401_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='api.Post'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.CharField(choices=[(-1, 'DISLIKE_VALUE'), (0, 'DEFAULT_VALUE'), (1, 'LIKE_VALUE')], max_length=1),
        ),
    ]
