# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-01 12:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170407_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.SmallIntegerField(default=None, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
