# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20170501_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
